name = "Nathan Lambertson"
fav_food = "Vietnamese"
middle_name = "Kirk"
age = 37
year_born = 1986
fav_num = 23
local_news_radio = 89.9
buck_n_quarter = 1.25
body_temp = 98.6
sunny = true
hot = true
rain = false
